use crate::config::{self, JagexAccountConfig};
use crate::platforms::{log_platform_error, log_platform_info, PlatformService, SetupStatus};
use crate::{AppContext, AppCtx};
use serde::Serialize;
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::{Mutex, OnceLock};
use uuid::Uuid;

const JAGEX_PROCESS_NAMES: &[&str] = &["JagexLauncher.exe"];
const JAGEX_EXECUTABLE_NAME: &str = "JagexLauncher.exe";
const JAGEX_SETUP_TTL_MS: u64 = 5 * 60 * 1000;
const POST_KILL_SETTLE_MS: u64 = 500;
/// Longest we wait for the launcher to flush its auth files to disk and exit
/// after a quit request before validating the snapshot source.
const SETUP_QUIT_TIMEOUT_MS: u32 = 8000;

/// Per-account files that live directly under %LOCALAPPDATA%\jagex launcher.
const SETTINGS_JSON: &str = "settings.json";
const LAUNCHER_JSON: &str = "launcher-win.production.json";

/// The launcher stores its Credential Manager entry as a DPAPI blob at this
/// fixed file name under %LOCALAPPDATA%\Microsoft\Credentials. The blob is
/// already user-bound encrypted; we snapshot and restore it as an opaque file
/// and never decrypt it ourselves.
const CRED_BLOB_LIVE_NAME: &str = "C5F6B4FF052E05B4F26961945E953169";

/// Snapshot names inside an account's cache directory.
const SNAP_AUTH: &str = "auth";
const SNAP_CRED_BLOB: &str = "credman_blob.bin";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct JagexAccount {
    pub account_id: String,
    pub label: String,
    pub last_used_at: Option<u64>,
    pub snapshot_saved: bool,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JagexStartupSnapshot {
    pub accounts: Vec<JagexAccount>,
    pub current_account: String,
}

// ---------------------------------------------------------------------------
// Setup job tracking
// ---------------------------------------------------------------------------

#[derive(Clone)]
struct JagexSetupJob {
    last_touched_at: u64,
}

fn setup_jobs() -> &'static Mutex<HashMap<String, JagexSetupJob>> {
    static JOBS: OnceLock<Mutex<HashMap<String, JagexSetupJob>>> = OnceLock::new();
    JOBS.get_or_init(|| Mutex::new(HashMap::new()))
}

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

fn local_app_data_dir() -> Result<PathBuf, String> {
    let local_app_data =
        env::var("LOCALAPPDATA").map_err(|_| "LOCALAPPDATA is not available".to_string())?;
    Ok(PathBuf::from(local_app_data))
}

fn jagex_data_dir() -> Result<PathBuf, String> {
    Ok(local_app_data_dir()?.join("jagex launcher"))
}

fn jagex_auth_dir() -> Result<PathBuf, String> {
    Ok(jagex_data_dir()?.join("auth"))
}

fn credential_blob_path() -> Result<PathBuf, String> {
    Ok(local_app_data_dir()?
        .join("Microsoft")
        .join("Credentials")
        .join(CRED_BLOB_LIVE_NAME))
}

fn jagex_default_executable() -> Option<PathBuf> {
    for var in ["ProgramFiles(x86)", "ProgramFiles"] {
        if let Ok(pf) = env::var(var) {
            let path = PathBuf::from(&pf)
                .join("Jagex Launcher")
                .join(JAGEX_EXECUTABLE_NAME);
            if path.is_file() {
                return Some(path);
            }
        }
    }
    None
}

fn resolve_executable(app_handle: &dyn AppContext) -> Result<PathBuf, String> {
    let cfg = config::load_config(app_handle);
    let override_path = cfg.jagex.path_override.trim().to_string();
    if !override_path.is_empty() {
        let p = PathBuf::from(&override_path);
        if p.is_file() {
            return Ok(p);
        }
        let candidate = p.join(JAGEX_EXECUTABLE_NAME);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }

    if let Some(exe) = jagex_default_executable() {
        return Ok(exe);
    }

    Err("Could not locate Jagex Launcher executable".into())
}

// ---------------------------------------------------------------------------
// Synthetic account ids
// ---------------------------------------------------------------------------

/// Jagex writes no readable account id anywhere, so ids are generated by us
/// when an account is captured (TcNo does the same with an id file).
fn generate_account_id() -> String {
    Uuid::new_v4().simple().to_string()
}

fn is_valid_jagex_account_id(s: &str) -> bool {
    // Synthetic ids are 32-char hex UUIDs. The id is joined into filesystem
    // paths (auth_cache_dir), so restrict the charset and length to keep path
    // traversal out.
    !s.is_empty() && s.len() <= 64 && s.chars().all(|c| c.is_ascii_alphanumeric())
}

// ---------------------------------------------------------------------------
// Auth snapshot (encrypted files + auth directory + credential blob)
// ---------------------------------------------------------------------------

fn auth_cache_dir(app_handle: &dyn AppContext, account_id: &str) -> Result<PathBuf, String> {
    let base = crate::storage::jagex_snapshots_dir(app_handle)?.join(account_id);
    Ok(base)
}

/// Magic header identifying an encrypted snapshot file (shared with Riot/Epic).
const ENCRYPTED_HEADER: &[u8] = b"ACCS";

/// Copy a file and encrypt its contents (DPAPI on Windows, keyring token elsewhere).
fn encrypted_copy_file(source: &Path, dest: &Path) -> Result<(), String> {
    let data = fs::read(source).map_err(|e| format!("Could not read {}: {e}", source.display()))?;
    let encrypted = crate::os::encrypt_bytes(&data)
        .map_err(|e| format!("Could not encrypt {}: {e}", source.display()))?;
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Could not create directory {}: {e}", parent.display()))?;
    }
    let mut out = Vec::with_capacity(ENCRYPTED_HEADER.len() + encrypted.len());
    out.extend_from_slice(ENCRYPTED_HEADER);
    out.extend_from_slice(&encrypted);
    fs::write(dest, &out).map_err(|e| format!("Could not write {}: {e}", dest.display()))
}

/// Copy a file, decrypting if it has the header (legacy plaintext files pass through).
fn decrypted_copy_file(source: &Path, dest: &Path) -> Result<(), String> {
    let data = fs::read(source).map_err(|e| format!("Could not read {}: {e}", source.display()))?;
    let content = if data.starts_with(ENCRYPTED_HEADER) {
        crate::os::decrypt_bytes(&data[ENCRYPTED_HEADER.len()..])
            .map_err(|e| format!("Could not decrypt {}: {e}", source.display()))?
    } else {
        data
    };
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Could not create directory {}: {e}", parent.display()))?;
    }
    fs::write(dest, &content).map_err(|e| format!("Could not write {}: {e}", dest.display()))
}

/// Release the OS-keyring entry an encrypted snapshot file points at (no-op on
/// Windows DPAPI). Legacy plaintext files have no header and own no secret.
fn delete_encrypted_file_secret(path: &Path) {
    let Ok(data) = fs::read(path) else {
        return;
    };
    if data.starts_with(ENCRYPTED_HEADER) {
        let _ = crate::os::delete_bytes(&data[ENCRYPTED_HEADER.len()..]);
    }
}

/// Recursively copy a directory tree, encrypting every file. Missing sources are
/// a no-op (the account may never have populated that directory).
fn encrypted_copy_dir(source: &Path, dest: &Path) -> Result<(), String> {
    if !source.exists() {
        return Ok(());
    }
    fs::create_dir_all(dest)
        .map_err(|e| format!("Could not create directory {}: {e}", dest.display()))?;
    for entry in fs::read_dir(source)
        .map_err(|e| format!("Could not read directory {}: {e}", source.display()))?
    {
        let entry = entry.map_err(|e| format!("Could not read directory entry: {e}"))?;
        let file_type = entry
            .file_type()
            .map_err(|e| format!("Could not read file type: {e}"))?;
        let src_path = entry.path();
        let dst_path = dest.join(entry.file_name());
        if file_type.is_dir() {
            encrypted_copy_dir(&src_path, &dst_path)?;
        } else if file_type.is_file() {
            encrypted_copy_file(&src_path, &dst_path)?;
        }
        // Symlinks and other special entries are skipped by design.
    }
    Ok(())
}

/// Recursively copy an encrypted snapshot tree back to disk, decrypting files.
fn decrypted_copy_dir(source: &Path, dest: &Path) -> Result<(), String> {
    if !source.exists() {
        return Ok(());
    }
    fs::create_dir_all(dest)
        .map_err(|e| format!("Could not create directory {}: {e}", dest.display()))?;
    for entry in fs::read_dir(source)
        .map_err(|e| format!("Could not read directory {}: {e}", source.display()))?
    {
        let entry = entry.map_err(|e| format!("Could not read directory entry: {e}"))?;
        let file_type = entry
            .file_type()
            .map_err(|e| format!("Could not read file type: {e}"))?;
        let src_path = entry.path();
        let dst_path = dest.join(entry.file_name());
        if file_type.is_dir() {
            decrypted_copy_dir(&src_path, &dst_path)?;
        } else if file_type.is_file() {
            decrypted_copy_file(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Snapshot a live session directory: drop the stale snapshot, then encrypt a
/// fresh copy of the source tree. A missing source just clears the snapshot.
fn save_dir_snapshot(source: &Path, snapshot_dir: &Path) -> Result<(), String> {
    let _ = fs::remove_dir_all(snapshot_dir);
    encrypted_copy_dir(source, snapshot_dir)
}

/// Restore a session directory from its encrypted snapshot. Stage a decrypted
/// copy next to the live directory first, then swap it in, so a mid-restore
/// failure never leaves the live directory half-populated with a mix of the
/// outgoing and incoming account's files. A missing snapshot is a no-op.
fn restore_dir_snapshot(snapshot_dir: &Path, live_dir: &Path) -> Result<(), String> {
    if !snapshot_dir.exists() {
        return Ok(());
    }
    let mut staging_name = live_dir.file_name().unwrap_or_default().to_os_string();
    staging_name.push(".accshift-restore-tmp");
    let staging = live_dir.with_file_name(staging_name);
    let _ = fs::remove_dir_all(&staging);

    decrypted_copy_dir(snapshot_dir, &staging)?;

    if live_dir.exists() {
        fs::remove_dir_all(live_dir)
            .map_err(|e| format!("Could not clear {}: {e}", live_dir.display()))?;
    }
    if let Some(parent) = live_dir.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Could not create directory {}: {e}", parent.display()))?;
    }
    match fs::rename(&staging, live_dir) {
        Ok(()) => Ok(()),
        Err(_) => {
            // Cross-volume rename or a lingering lock: fall back to a plain copy
            // of the already-decrypted staging tree, then drop the staging dir.
            crate::fs_utils::copy_dir_recursive(&staging, live_dir, &[])?;
            let _ = fs::remove_dir_all(&staging);
            Ok(())
        }
    }
}

/// Free any keyring entries every encrypted file under `dir` points at before
/// the directory is removed (no-op under Windows DPAPI).
fn free_dir_secrets(dir: &Path) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            free_dir_secrets(&path);
        } else {
            delete_encrypted_file_secret(&path);
        }
    }
}

/// Snapshot a single live file. A missing source drops the stale snapshot so a
/// later restore cannot resurrect another account's file.
fn save_file_snapshot(source: &Path, dest: &Path) -> Result<(), String> {
    delete_encrypted_file_secret(dest);
    if source.is_file() {
        encrypted_copy_file(source, dest)
    } else {
        let _ = fs::remove_file(dest);
        Ok(())
    }
}

fn save_auth_snapshot(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let cache_dir = auth_cache_dir(app_handle, account_id)?;
    fs::create_dir_all(&cache_dir).map_err(|e| format!("Could not create auth cache dir: {e}"))?;

    let data_dir = jagex_data_dir()?;
    save_file_snapshot(
        &data_dir.join(SETTINGS_JSON),
        &cache_dir.join(SETTINGS_JSON),
    )?;
    save_file_snapshot(
        &data_dir.join(LAUNCHER_JSON),
        &cache_dir.join(LAUNCHER_JSON),
    )?;
    save_file_snapshot(&credential_blob_path()?, &cache_dir.join(SNAP_CRED_BLOB))?;
    save_dir_snapshot(&jagex_auth_dir()?, &cache_dir.join(SNAP_AUTH))?;

    Ok(())
}

fn restore_auth_snapshot(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let cache_dir = auth_cache_dir(app_handle, account_id)?;

    if !cache_dir.exists() {
        return Err(format!(
            "No auth snapshot found for account {account_id}. Add this account through setup first."
        ));
    }

    let data_dir = jagex_data_dir()?;
    fs::create_dir_all(&data_dir).map_err(|e| format!("Could not create Jagex data dir: {e}"))?;
    for name in [SETTINGS_JSON, LAUNCHER_JSON] {
        let source = cache_dir.join(name);
        if source.exists() {
            decrypted_copy_file(&source, &data_dir.join(name))?;
        }
    }

    let blob_snapshot = cache_dir.join(SNAP_CRED_BLOB);
    if blob_snapshot.exists() {
        let live = credential_blob_path()?;
        // The Credentials store marks its files hidden/system, and File::create
        // refuses to truncate a hidden file on Windows. Drop it before writing.
        let _ = fs::remove_file(&live);
        decrypted_copy_file(&blob_snapshot, &live)?;
    }

    restore_dir_snapshot(&cache_dir.join(SNAP_AUTH), &jagex_auth_dir()?)?;

    Ok(())
}

fn has_auth_snapshot(app_handle: &dyn AppContext, account_id: &str) -> bool {
    if let Ok(cache_dir) = auth_cache_dir(app_handle, account_id) {
        cache_dir.join(SNAP_AUTH).exists()
            || cache_dir.join(SETTINGS_JSON).exists()
            || cache_dir.join(SNAP_CRED_BLOB).exists()
    } else {
        false
    }
}

/// Clear the live session so a fresh sign-in starts clean. Used only on the
/// setup path, never on switch (switch restores these from a snapshot).
/// settings.json / launcher-win.production.json are left in place: they hold
/// launcher preferences and do not keep a session signed in.
fn delete_auth_files() -> Result<(), String> {
    if let Ok(dir) = jagex_auth_dir() {
        let _ = fs::remove_dir_all(&dir);
    }
    if let Ok(blob) = credential_blob_path() {
        let _ = fs::remove_file(&blob);
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Login detection
// ---------------------------------------------------------------------------

fn dir_has_nonempty_file(dir: &Path) -> bool {
    let Ok(entries) = fs::read_dir(dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if dir_has_nonempty_file(&path) {
                return true;
            }
        } else if fs::metadata(&path).map(|m| m.len() > 0).unwrap_or(false) {
            return true;
        }
    }
    false
}

/// True once a sign-in has produced session material. Setup deletes both the
/// auth directory and the credential blob up front, so their reappearance is
/// the only signal we have that the user completed the login (Jagex exposes no
/// account id to poll for).
fn login_artifacts_present() -> bool {
    let Ok(auth_dir) = jagex_auth_dir() else {
        return false;
    };
    let Ok(blob) = credential_blob_path() else {
        return false;
    };
    let blob_ok = fs::metadata(&blob).map(|m| m.len() > 0).unwrap_or(false);
    blob_ok && dir_has_nonempty_file(&auth_dir)
}

// ---------------------------------------------------------------------------
// Process management
// ---------------------------------------------------------------------------

fn is_jagex_running() -> bool {
    JAGEX_PROCESS_NAMES
        .iter()
        .any(|name| crate::os::is_process_running(name))
}

fn kill_jagex() {
    for process_name in JAGEX_PROCESS_NAMES {
        let _ = crate::os::kill_process(process_name);
    }
}

/// Kill the launcher and wait for it to actually exit, so callers don't race
/// its exit-time flush of the auth files to disk.
fn quit_jagex_and_wait() {
    if !is_jagex_running() {
        return;
    }
    kill_jagex();
    for process_name in JAGEX_PROCESS_NAMES {
        crate::os::wait_for_process_exit(process_name, SETUP_QUIT_TIMEOUT_MS);
    }
    std::thread::sleep(std::time::Duration::from_millis(POST_KILL_SETTLE_MS));
}

fn launch_jagex(app_handle: &dyn AppContext) -> Result<(), String> {
    let executable = resolve_executable(app_handle)?;
    let mut command = Command::new(&executable);
    if let Some(install_dir) = executable.parent() {
        command.current_dir(install_dir);
    }
    command.spawn().map_err(|e| {
        format!(
            "Could not launch Jagex Launcher {}: {e}",
            executable.display()
        )
    })?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Account management
// ---------------------------------------------------------------------------

fn validate_account_id(id: &str) -> Result<String, String> {
    let trimmed = id.trim().to_string();
    if trimmed.is_empty() {
        return Err("Empty Jagex account ID".into());
    }
    // Strict format check: the id is joined into filesystem paths
    // (auth_cache_dir), so anything outside the synthetic id charset must be
    // rejected.
    if !is_valid_jagex_account_id(&trimmed) {
        return Err(format!("Invalid Jagex account ID: {trimmed}"));
    }
    Ok(trimmed)
}

/// Accounts only exist in the config: Jagex leaves no on-disk id to discover,
/// so every account was created by our own setup flow.
fn read_accounts(app_handle: &dyn AppContext) -> Result<Vec<JagexAccount>, String> {
    let cfg = config::load_config(app_handle);

    let mut seen = HashSet::new();
    let mut accounts = Vec::new();
    for account in &cfg.jagex.accounts {
        let key = account.account_id.trim().to_string();
        if key.is_empty() || !seen.insert(key.clone()) {
            continue;
        }
        accounts.push(JagexAccount {
            account_id: key.clone(),
            label: account.label.trim().to_string(),
            last_used_at: account.last_used_at,
            snapshot_saved: has_auth_snapshot(app_handle, &key),
        });
    }

    Ok(accounts)
}

/// The current account is whichever id was last switched to or captured by
/// setup. There is no live source of truth to cross-check against.
fn read_current_account(app_handle: &dyn AppContext) -> Option<String> {
    let cfg = config::load_config(app_handle);
    let current = cfg.jagex.current_account.trim().to_string();
    if current.is_empty() || !is_valid_jagex_account_id(&current) {
        None
    } else {
        Some(current)
    }
}

fn remember_account_usage(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let account_id = validate_account_id(account_id)?;
    let key = account_id.clone();
    let now = super::now_unix_ms();

    config::update_config(app_handle, |cfg| {
        if let Some(existing) = cfg
            .jagex
            .accounts
            .iter_mut()
            .find(|a| a.account_id.trim() == key)
        {
            existing.last_used_at = Some(now);
        } else {
            cfg.jagex.accounts.push(JagexAccountConfig {
                account_id: account_id.clone(),
                label: String::new(),
                last_used_at: Some(now),
            });
        }
    })
}

/// Record usage of the current account and refresh its snapshot before its
/// live session is overwritten.
///
/// A session signed in outside accshift has no known id (Jagex writes none),
/// so with no current account in the config there is nothing we can attribute
/// the live session to and capture is skipped.
///
/// Returns Err when a current account IS recorded but its snapshot could not
/// be saved, so the caller can abort before killing the launcher or replacing
/// the live session.
fn capture_current_account(app_handle: &dyn AppContext) -> Result<(), String> {
    let Some(current_id) = read_current_account(app_handle) else {
        return Ok(());
    };
    let _ = remember_account_usage(app_handle, &current_id);
    save_auth_snapshot(app_handle, &current_id)
}

fn forget_account_metadata(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let key = account_id.trim().to_string();
    config::update_config(app_handle, |cfg| {
        cfg.jagex.accounts.retain(|a| a.account_id.trim() != key);
        if cfg.jagex.current_account.trim() == key {
            cfg.jagex.current_account.clear();
        }
    })?;

    // Remove cached auth snapshot. Only touch the filesystem for ids in the
    // canonical synthetic format: the id is joined into the snapshot path.
    if is_valid_jagex_account_id(&key) {
        if let Ok(cache_dir) = auth_cache_dir(app_handle, &key) {
            // Free the OS-keyring entries every encrypted file points at before
            // deleting them (no-op under Windows DPAPI).
            delete_encrypted_file_secret(&cache_dir.join(SETTINGS_JSON));
            delete_encrypted_file_secret(&cache_dir.join(LAUNCHER_JSON));
            delete_encrypted_file_secret(&cache_dir.join(SNAP_CRED_BLOB));
            free_dir_secrets(&cache_dir.join(SNAP_AUTH));
            let _ = fs::remove_dir_all(&cache_dir);
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Public operations
// ---------------------------------------------------------------------------

pub fn get_accounts(app_handle: &dyn AppContext) -> Result<Vec<JagexAccount>, String> {
    read_accounts(app_handle)
}

pub fn get_startup_snapshot(app_handle: &dyn AppContext) -> Result<JagexStartupSnapshot, String> {
    let accounts = read_accounts(app_handle)?;
    let current = read_current_account(app_handle).unwrap_or_default();
    Ok(JagexStartupSnapshot {
        accounts,
        current_account: current,
    })
}

pub fn get_current_account(app_handle: &dyn AppContext) -> Result<String, String> {
    Ok(read_current_account(app_handle).unwrap_or_default())
}

pub fn switch_account(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let account_id = validate_account_id(account_id)?;
    log_platform_info(
        app_handle,
        "jagex.switch_account",
        "Jagex switch requested",
        format!("target={}", super::redact_id(&account_id)),
    );

    // Always record + snapshot the current account before switching away.
    // Abort here if the snapshot cannot be saved: proceeding would kill the
    // launcher and overwrite this account's live session with the target's,
    // stranding it signed out with no backup to restore later.
    capture_current_account(app_handle)?;

    // Clear the current marker before touching live files: if the restore
    // fails midway the live state is a mix of two accounts and must not be
    // captured into either snapshot on a later switch.
    config::update_config(app_handle, |cfg| cfg.jagex.current_account.clear())?;

    // Kill the launcher and wait for it to actually exit before touching files.
    quit_jagex_and_wait();

    // Restore target account's session
    restore_auth_snapshot(app_handle, &account_id)?;

    // Record usage and mark the target as the live session.
    remember_account_usage(app_handle, &account_id)?;
    config::update_config(app_handle, |cfg| {
        cfg.jagex.current_account = account_id.clone();
    })?;

    // Relaunch
    let result = launch_jagex(app_handle);

    match &result {
        Ok(()) => log_platform_info(
            app_handle,
            "jagex.switch_account",
            "Jagex switch completed",
            format!("target={}", super::redact_id(&account_id)),
        ),
        Err(error) => log_platform_error(
            app_handle,
            "jagex.switch_account",
            "Jagex switch failed",
            format!("target={}; error={error}", super::redact_id(&account_id)),
        ),
    }

    result
}

pub fn begin_account_setup(app_handle: &dyn AppContext) -> Result<SetupStatus, String> {
    log_platform_info(
        app_handle,
        "jagex.begin_account_setup",
        "Jagex account setup requested",
        "",
    );

    // Record + snapshot the current account before clearing its session. Abort
    // if the snapshot cannot be saved: proceeding would kill the launcher and
    // delete the live session with no backup to restore later.
    capture_current_account(app_handle)?;

    let setup_id = format!("jagex-setup-{}", Uuid::new_v4());
    let created_at = super::now_unix_ms();

    let mut jobs = setup_jobs()
        .lock()
        .map_err(|_| "Jagex setup storage is unavailable".to_string())?;
    jobs.retain(|_, j| !super::setup_expired(j.last_touched_at, JAGEX_SETUP_TTL_MS));
    jobs.insert(
        setup_id.clone(),
        JagexSetupJob {
            last_touched_at: created_at,
        },
    );
    drop(jobs);

    // Kill the launcher, clear the live session to force the login screen.
    quit_jagex_and_wait();
    delete_auth_files()?;
    // Nobody is signed in until the setup completes.
    config::update_config(app_handle, |cfg| cfg.jagex.current_account.clear())?;

    // Relaunch
    launch_jagex(app_handle).inspect_err(|e| {
        log_platform_error(
            app_handle,
            "jagex.begin_account_setup",
            "Jagex setup launch failed",
            e,
        );
    })?;

    Ok(super::make_setup_status(
        &setup_id,
        "waiting_for_client",
        "",
        "",
        "",
    ))
}

pub fn get_account_setup_status(
    app_handle: &dyn AppContext,
    setup_id: &str,
) -> Result<SetupStatus, String> {
    {
        let mut jobs = setup_jobs()
            .lock()
            .map_err(|_| "Jagex setup storage is unavailable".to_string())?;
        jobs.retain(|_, j| !super::setup_expired(j.last_touched_at, JAGEX_SETUP_TTL_MS));
        let Some(job) = jobs.get_mut(setup_id) else {
            return Err("Jagex setup session not found".into());
        };
        job.last_touched_at = super::now_unix_ms();
    }

    // Setup deleted the auth dir and credential blob, so fresh session
    // material means the user signed in.
    if login_artifacts_present() {
        // Quit the launcher so any in-memory session state flushes to disk,
        // then re-check before capturing.
        quit_jagex_and_wait();

        if !login_artifacts_present() {
            return Ok(super::make_setup_status(
                setup_id,
                "waiting_for_login",
                "",
                "",
                "",
            ));
        }

        let key = generate_account_id();
        save_auth_snapshot(app_handle, &key)?;
        remember_account_usage(app_handle, &key)?;
        config::update_config(app_handle, |cfg| {
            cfg.jagex.current_account = key.clone();
        })?;

        if let Ok(mut jobs) = setup_jobs().lock() {
            jobs.remove(setup_id);
        }

        // No display name: Jagex exposes none, the user labels the account.
        return Ok(super::make_setup_status(setup_id, "ready", key, "", ""));
    }

    if is_jagex_running() {
        return Ok(super::make_setup_status(
            setup_id,
            "waiting_for_login",
            "",
            "",
            "",
        ));
    }

    Ok(super::make_setup_status(
        setup_id,
        "waiting_for_client",
        "",
        "",
        "",
    ))
}

pub fn cancel_account_setup(setup_id: &str) -> Result<(), String> {
    let mut jobs = setup_jobs()
        .lock()
        .map_err(|_| "Jagex setup storage is unavailable".to_string())?;
    jobs.retain(|_, j| !super::setup_expired(j.last_touched_at, JAGEX_SETUP_TTL_MS));
    jobs.remove(setup_id);
    Ok(())
}

pub fn forget_account(app_handle: &dyn AppContext, account_id: &str) -> Result<(), String> {
    let account_id = validate_account_id(account_id)?;
    forget_account_metadata(app_handle, &account_id)
}

pub fn set_account_label(
    app_handle: &dyn AppContext,
    account_id: &str,
    label: &str,
) -> Result<(), String> {
    let account_id = validate_account_id(account_id)?;
    let key = account_id.clone();
    let label = label.trim().to_string();

    config::update_config(app_handle, |cfg| {
        if let Some(existing) = cfg
            .jagex
            .accounts
            .iter_mut()
            .find(|a| a.account_id.trim() == key)
        {
            existing.label = label.clone();
        } else {
            cfg.jagex.accounts.push(JagexAccountConfig {
                account_id: account_id.clone(),
                label,
                last_used_at: None,
            });
        }
    })
}

pub fn get_jagex_path(app_handle: &dyn AppContext) -> Result<String, String> {
    let cfg = config::load_config(app_handle);
    if !cfg.jagex.path_override.trim().is_empty() {
        return Ok(cfg.jagex.path_override);
    }
    resolve_executable(app_handle).map(|p| p.to_string_lossy().to_string())
}

pub fn set_jagex_path(app_handle: &dyn AppContext, path: &str) -> Result<(), String> {
    let path = path.trim().to_string();
    config::update_config(app_handle, |cfg| {
        cfg.jagex.path_override = path;
    })
}

pub fn select_jagex_path() -> Result<String, String> {
    crate::os::select_file(
        "Select Jagex Launcher executable",
        "Executable files (*.exe)|*.exe|All files (*.*)|*.*",
    )
    .map_err(|e| e.to_string())
}

// ---------------------------------------------------------------------------
// PlatformService implementation
// ---------------------------------------------------------------------------

pub struct JagexService;

pub static JAGEX_SERVICE: JagexService = JagexService;

impl PlatformService for JagexService {
    fn get_accounts(&self, app: AppCtx) -> Result<Value, String> {
        let accounts = get_accounts(&app)?;
        serde_json::to_value(accounts).map_err(|e| e.to_string())
    }

    fn get_startup_snapshot(&self, app: AppCtx) -> Result<Value, String> {
        let snapshot = get_startup_snapshot(&app)?;
        serde_json::to_value(snapshot).map_err(|e| e.to_string())
    }

    fn get_current_account(&self, app: AppCtx) -> Result<String, String> {
        get_current_account(&app)
    }

    fn switch_account(&self, app: AppCtx, account_id: &str, _params: Value) -> Result<(), String> {
        switch_account(&app, account_id)
    }

    fn forget_account(&self, app: AppCtx, account_id: &str) -> Result<(), String> {
        forget_account(&app, account_id)
    }

    fn begin_setup(&self, app: AppCtx, _params: Value) -> Result<SetupStatus, String> {
        begin_account_setup(&app)
    }

    fn get_setup_status(&self, app: AppCtx, setup_id: &str) -> Result<SetupStatus, String> {
        get_account_setup_status(&app, setup_id)
    }

    fn cancel_setup(&self, _app: AppCtx, setup_id: &str) -> Result<(), String> {
        cancel_account_setup(setup_id)
    }

    fn get_path(&self, app: AppCtx) -> Result<String, String> {
        get_jagex_path(&app)
    }

    fn set_path(&self, app: AppCtx, path: &str) -> Result<(), String> {
        set_jagex_path(&app, path)
    }

    fn select_path(&self) -> Result<String, String> {
        select_jagex_path()
    }

    fn set_account_label(&self, app: AppCtx, account_id: &str, label: &str) -> Result<(), String> {
        set_account_label(&app, account_id, label)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_id_is_valid() {
        let id = generate_account_id();
        assert_eq!(id.len(), 32);
        assert!(is_valid_jagex_account_id(&id));
    }

    #[test]
    fn valid_jagex_id_alphanumeric() {
        assert!(is_valid_jagex_account_id(
            "a3f0c2d14b5e46789a0b1c2d3e4f5061"
        ));
    }

    #[test]
    fn invalid_jagex_id_empty() {
        assert!(!is_valid_jagex_account_id(""));
    }

    #[test]
    fn invalid_jagex_id_too_long() {
        assert!(!is_valid_jagex_account_id(&"a".repeat(65)));
    }

    #[test]
    fn invalid_jagex_id_bad_chars() {
        assert!(!is_valid_jagex_account_id("abc-123"));
        assert!(!is_valid_jagex_account_id("abc.123"));
    }

    #[test]
    fn validate_account_id_trims() {
        let result = validate_account_id("  a3f0c2d14b5e46789a0b1c2d3e4f5061  ");
        assert_eq!(result.unwrap(), "a3f0c2d14b5e46789a0b1c2d3e4f5061");
    }

    #[test]
    fn validate_account_id_empty_fails() {
        assert!(validate_account_id("").is_err());
    }

    #[test]
    fn validate_account_id_rejects_path_traversal() {
        assert!(validate_account_id("..\\..\\evil").is_err());
        assert!(validate_account_id("../../evil").is_err());
        assert!(validate_account_id("a/b").is_err());
    }

    fn scratch_dir(tag: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "accshift-jagex-test-{}-{}-{:?}",
            tag,
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn encrypted_header_is_accs() {
        assert_eq!(ENCRYPTED_HEADER, b"ACCS");
    }

    #[test]
    fn decrypted_copy_passes_legacy_plaintext_through() {
        // Snapshots without a header must restore byte-for-byte without ever
        // calling the OS decrypt backend.
        let dir = scratch_dir("legacy-plaintext");
        let source = dir.join("settings.json");
        let dest = dir.join("restored.json");
        let body: &[u8] = b"{\"token\":\"legacy-value\"}";
        fs::write(&source, body).unwrap();

        decrypted_copy_file(&source, &dest).unwrap();

        assert_eq!(fs::read(&dest).unwrap().as_slice(), body);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dir_has_nonempty_file_ignores_empty_and_missing() {
        let dir = scratch_dir("nonempty-detect");
        assert!(!dir_has_nonempty_file(&dir.join("missing")));
        assert!(!dir_has_nonempty_file(&dir));

        fs::write(dir.join("empty.bin"), b"").unwrap();
        assert!(!dir_has_nonempty_file(&dir));

        let nested = dir.join("nested");
        fs::create_dir_all(&nested).unwrap();
        fs::write(nested.join("token.bin"), b"data").unwrap();
        assert!(dir_has_nonempty_file(&dir));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn save_file_snapshot_drops_stale_snapshot_when_source_missing() {
        let dir = scratch_dir("stale-snapshot");
        let source = dir.join("missing-source.json");
        let dest = dir.join("snapshot.json");
        fs::write(&dest, b"stale").unwrap();

        save_file_snapshot(&source, &dest).unwrap();

        assert!(!dest.exists());
        let _ = fs::remove_dir_all(&dir);
    }
}
